#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

MONITOR_NAME="VGA1"
EXTERNAL_MONITOR_NAME="HDMI1"

STATUS_EXTERNAL_MONITOR=$(xrandr --query | grep $EXTERNAL_MONITOR_NAME)
if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
    xrandr --output $MONITOR_NAME --primary --mode 1600x900  --output $EXTERNAL_MONITOR_NAME --mode 1360x768 --rotate normal --left-of $MONITOR_NAME
else
    xrandr --output $EXTERNAL_MONITOR_NAME --off
fi

if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
	bspc monitor $MONITOR_NAME -d 1 2 3 4 5
	bspc monitor $EXTERNAL_MONITOR_NAME -d 6 7 8 9 10
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         0
bspc config window_gap          20
bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color     "#D8DEE9"
bspc config normal_border_color      "#3B4252"

bspc rule -a Nitrogen state=floating
bspc rule -a Blueberry.py state=floating
bspc rule -a Bitwarden state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a "Kvantum Manager" state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Galculator state=floating
bspc rule -a Pamac-manager state=floating
bspc rule -a qBittorrent state=floating
bspc rule -a Mousepad state=floating
bspc rule -a GNvim state=tiled
bspc rule -a Lightdm-gtk-greeter-settings state=floating
bspc rule -a File-roller state=floating
bspc rule -a Ristretto state=floating

picom -b &
xsetroot -cursor_name left_ptr &
ibus-daemon -drxR &
dunst &
lxpolkit &
blueberry-tray &
parcellite &
conky &
playerctld daemon &

if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
	$HOME/.config/polybar/launch2.sh
else
	$HOME/.config/polybar/launch.sh
fi

nitrogen --restore &
kdeconnect-indicator &
flameshot &
discord --start-minimized &
